// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
'use client';
import { GhlPage } from '@/components/GhlPage';
import { SCRIPTS } from './scripts';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const content: { HEAD_HTML: string; BODY_HTML: string } | null = typeof window === 'undefined' ? require('./content') : null;

export default function PageClient() {
  return <GhlPage headHtml={content ? content.HEAD_HTML : ''} bodyHtml={content ? content.BODY_HTML : ''} scripts={SCRIPTS} />;
}
