// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Duerme Mejor y Reclínate con Inteligencia con el Zcliner®",
  "description": "Descubre una nueva forma de descansar con el SleepRecliner (Zcliner®) de Flexsteel, disponible exclusivamente en Snooze Mattress + Wellness en McAllen. Mucho más que un reclinable, el Zcliner® combina tecnología de confort avanzada con posiciones terapéuticas para ayudarte a relajarte, aliviar la presión y descansar mejor.",
  "alternates": {
    "canonical": "/es/sleep-recliner",
    "languages": {
      "en": "/sleep-recliner",
      "es": "/es/sleep-recliner",
      "x-default": "/sleep-recliner"
    }
  },
  "openGraph": {
    "title": "Duerme Mejor y Reclínate con Inteligencia con el Zcliner®",
    "description": "Descubre una nueva forma de descansar con el SleepRecliner (Zcliner®) de Flexsteel, disponible exclusivamente en Snooze Mattress + Wellness en McAllen. Mucho más que un reclinable, el Zcliner® combina tecnología de confort avanzada con posiciones terapéuticas para ayudarte a relajarte, aliviar la presión y descansar mejor.",
    "url": "/es/sleep-recliner",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
