// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Contáctanos",
  "description": "¿Tienes preguntas? Escríbenos y nuestro equipo te responderá muy pronto.",
  "alternates": {
    "canonical": "/es/optin-page",
    "languages": {
      "en": "/optin-page",
      "es": "/es/optin-page",
      "x-default": "/optin-page"
    }
  },
  "openGraph": {
    "title": "Contáctanos",
    "description": "¿Tienes preguntas? Escríbenos y nuestro equipo te responderá muy pronto.",
    "url": "/es/optin-page",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
