// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Best Mattresses  in McAllen",
  "description": "Finding the perfect mattress in McAllen doesn’t have to be overwhelming. At Snooze Mattress + Wellness, we make it simple and personal. From luxury comfort and advanced sleep technology to budget-friendly options, our McAllen showroom offers mattresses for every sleep style and budget.",
  "alternates": {
    "canonical": "/mattresses",
    "languages": {
      "en": "/mattresses",
      "es": "/es/mattresses",
      "x-default": "/mattresses"
    }
  },
  "openGraph": {
    "title": "Best Mattresses  in McAllen",
    "description": "Finding the perfect mattress in McAllen doesn’t have to be overwhelming. At Snooze Mattress + Wellness, we make it simple and personal. From luxury comfort and advanced sleep technology to budget-friendly options, our McAllen showroom offers mattresses for every sleep style and budget.",
    "url": "/mattresses",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
