// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Terms & Conditions",
  "description": "Welcome to Snooze Mattress + Wellness – Brownsville (“Company,” “we,” “us,” or “our”).\nBy accessing or using  (“Website”), you agree to the following Terms & Conditions. If you do not agree, please do not use this Website.",
  "alternates": {
    "canonical": "/terms-conditions",
    "languages": {
      "en": "/terms-conditions",
      "es": "/es/terms-conditions",
      "x-default": "/terms-conditions"
    }
  },
  "openGraph": {
    "title": "Terms & Conditions",
    "description": "Welcome to Snooze Mattress + Wellness – Brownsville (“Company,” “we,” “us,” or “our”).\nBy accessing or using  (“Website”), you agree to the following Terms & Conditions. If you do not agree, please do not use this Website.",
    "url": "/terms-conditions",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
