import { NextResponse, type NextRequest } from 'next/server';

// Generated by scripts/convert.mjs. The GoHighLevel runtime builds Google Fonts stylesheet URLs at run time
// (…/css?family=…); the bundles were patched to use /assets/gfonts-css instead of fonts.googleapis.com, and this
// middleware maps such a request onto the wget-named local copy (same naming as scripts/convert.mjs).
export const config = { matcher: ['/assets/gfonts-css/:path*'] };

function fnv1a(s: string) { let h = 0x811c9dc5; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; } return h.toString(16).padStart(8, '0'); }
function sanitizeSeg(seg: string) { let s = seg.replace(/[^A-Za-z0-9._-]/g, '_'); if (s.length > 100) { const ext = (seg.match(/\.[A-Za-z0-9]{1,8}$/) || [''])[0]; s = s.slice(0, 60) + '-' + fnv1a(seg) + ext; } return s; }
function winEscape(s: string) { return s.replace(/[\\|:?"*<>\x00-\x1f]/g, (c) => '%' + c.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0')); }

export function middleware(req: NextRequest) {
  const { pathname, search } = req.nextUrl;
  if (/^\/assets\/gfonts-css\/css2?$/.test(pathname) && search.length > 1) {
    const base = pathname.split('/').pop() as string;
    const url = req.nextUrl.clone();
    let query = search.slice(1);
    try { query = decodeURIComponent(query); } catch { /* keep as is */ }
    url.pathname = '/assets/gfonts-css/' + sanitizeSeg(base + '@' + winEscape(query) + '.css');
    url.search = '';
    return NextResponse.rewrite(url);
  }
  return NextResponse.next();
}
