// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Thank You",
  "description": "You’re on your way to better sleep—our Dream Mapping Coach will connect with you soon.",
  "alternates": {
    "canonical": "/thank/you",
    "languages": {
      "en": "/thank/you",
      "es": "/es/thank/you",
      "x-default": "/thank/you"
    }
  },
  "openGraph": {
    "title": "Thank You",
    "description": "You’re on your way to better sleep—our Dream Mapping Coach will connect with you soon.",
    "url": "/thank/you",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
