// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Infinity® Massage Chairs in McAllen",
  "description": "Infinity® Massage Chairs at Snooze Mattress + Wellness in McAllen deliver advanced massage technology designed to promote relaxation, recovery, and total-body wellness. Featuring zero-gravity positioning, full-body air compression, heated therapy, and precision massage rollers, Infinity massage chairs provide a spa-quality experience in the comfort of your home.",
  "alternates": {
    "canonical": "/massage-chairs",
    "languages": {
      "en": "/massage-chairs",
      "es": "/es/massage-chairs",
      "x-default": "/massage-chairs"
    }
  },
  "openGraph": {
    "title": "Infinity® Massage Chairs in McAllen",
    "description": "Infinity® Massage Chairs at Snooze Mattress + Wellness in McAllen deliver advanced massage technology designed to promote relaxation, recovery, and total-body wellness. Featuring zero-gravity positioning, full-body air compression, heated therapy, and precision massage rollers, Infinity massage chairs provide a spa-quality experience in the comfort of your home.",
    "url": "/massage-chairs",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/697a4541f215daeb1a4c3c11.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
