// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Sillas de Masaje Infinity® en Brownsville",
  "description": "Las sillas de masaje Infinity® de Snooze Mattress + Wellness en Brownsville ofrecen tecnología de masaje avanzada para relajarte, recuperarte y cuidar tu bienestar total. Con posición de gravedad cero, compresión de aire de cuerpo completo, terapia de calor y rodillos de masaje de precisión, las sillas Infinity te dan una experiencia de spa en la comodidad de tu casa.",
  "alternates": {
    "canonical": "/es/massage-chairs",
    "languages": {
      "en": "/massage-chairs",
      "es": "/es/massage-chairs",
      "x-default": "/massage-chairs"
    }
  },
  "openGraph": {
    "title": "Sillas de Masaje Infinity® en Brownsville",
    "description": "Las sillas de masaje Infinity® de Snooze Mattress + Wellness en Brownsville ofrecen tecnología de masaje avanzada para relajarte, recuperarte y cuidar tu bienestar total. Con posición de gravedad cero, compresión de aire de cuerpo completo, terapia de calor y rodillos de masaje de precisión, las sillas Infinity te dan una experiencia de spa en la comodidad de tu casa.",
    "url": "/es/massage-chairs",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a0dae8153630a3700.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
