// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "La Mejor Tienda de Colchones en McAllen, TX | Snooze Mattress McAllen",
  "description": "Nuestra tecnología Dream Mapping encuentra el colchón perfecto para tus necesidades, ¡en solo 5 minutos! Visítanos hoy en McAllen.",
  "keywords": [
    "Snooze",
    "dream mapping",
    "Snooze Mattress & Wellness",
    "personalized sleep profile",
    "mattress shopping",
    "sleep technology",
    "pressure mapping",
    "McAllen mattresses",
    "sleep solutions",
    "mattress recommendations",
    "sleep wellness",
    "sleep comfort",
    "custom pressure map",
    "innovative sleep technology"
  ],
  "authors": [
    {
      "name": "Snooze Mattress & Wellness"
    }
  ],
  "robots": "index, follow",
  "alternates": {
    "canonical": "/es/home-page",
    "languages": {
      "en": "/home-page",
      "es": "/es/home-page",
      "x-default": "/home-page"
    }
  },
  "openGraph": {
    "title": "La Mejor Tienda de Colchones en McAllen, TX | Snooze Mattress McAllen",
    "description": "Nuestra tecnología Dream Mapping encuentra el colchón perfecto para tus necesidades, ¡en solo 5 minutos! Visítanos hoy en McAllen.",
    "url": "/es/home-page",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/699c969010bc9c1e4d659063.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
