// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Discover What's Disrupting Your Sleep—From Home",
  "description": "Struggling with snoring, fatigue, or restless nights? The At-Home Sleep Test Kit by SleepCorner, available at Snooze Mattress + Wellness in McAllen, gives you answers without the hassle of a sleep lab. This FDA-cleared, easy-to-use test monitors your sleep patterns overnight and is reviewed by licensed sleep professionals to help identify potential sleep disorders like sleep apnea.",
  "alternates": {
    "canonical": "/at-home-sleep-test-kit-by-sleepcorner",
    "languages": {
      "en": "/at-home-sleep-test-kit-by-sleepcorner",
      "es": "/es/at-home-sleep-test-kit-by-sleepcorner",
      "x-default": "/at-home-sleep-test-kit-by-sleepcorner"
    }
  },
  "openGraph": {
    "title": "Discover What's Disrupting Your Sleep—From Home",
    "description": "Struggling with snoring, fatigue, or restless nights? The At-Home Sleep Test Kit by SleepCorner, available at Snooze Mattress + Wellness in McAllen, gives you answers without the hassle of a sleep lab. This FDA-cleared, easy-to-use test monitors your sleep patterns overnight and is reviewed by licensed sleep professionals to help identify potential sleep disorders like sleep apnea.",
    "url": "/at-home-sleep-test-kit-by-sleepcorner",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/6998cc589df4c153d0a468bf.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
