// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "¡Gracias por Agendar tu Cita de Dream Mapping!",
  "description": "¡Nuestros Sleep Coaches ya quieren conocerte y empezar juntos tu nueva etapa de mejor sueño!",
  "alternates": {
    "canonical": "/es/dream/map/thank/you",
    "languages": {
      "en": "/dream/map/thank/you",
      "es": "/es/dream/map/thank/you",
      "x-default": "/dream/map/thank/you"
    }
  },
  "openGraph": {
    "title": "¡Gracias por Agendar tu Cita de Dream Mapping!",
    "description": "¡Nuestros Sleep Coaches ya quieren conocerte y empezar juntos tu nueva etapa de mejor sueño!",
    "url": "/es/dream/map/thank/you",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e722007d7fffba435.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
