// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Protect Your Mattress, Protect Your Investment",
  "description": "A quality mattress deserves quality protection. At Snooze Mattress + Wellness in McAllen, our premium mattress protectors safeguard your bed against spills, stains, allergens, and everyday wear—all while maintaining the comfort and feel you love.",
  "alternates": {
    "canonical": "/mattress-protectors",
    "languages": {
      "en": "/mattress-protectors",
      "es": "/es/mattress-protectors",
      "x-default": "/mattress-protectors"
    }
  },
  "openGraph": {
    "title": "Protect Your Mattress, Protect Your Investment",
    "description": "A quality mattress deserves quality protection. At Snooze Mattress + Wellness in McAllen, our premium mattress protectors safeguard your bed against spills, stains, allergens, and everyday wear—all while maintaining the comfort and feel you love.",
    "url": "/mattress-protectors",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
