// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Sleep Better. Save More. Shop Local.",
  "description": "You’re in the right place. At Snooze Mattress + Wellness, we help you find the perfect mattress at the perfect price — without pressure, gimmicks, or confusing fine print. Whether you’re upgrading your master bedroom, shopping for a guest room, or finally replacing that sagging mattress, we make it simple, affordable, and comfortable.",
  "alternates": {
    "canonical": "/mattress-sales",
    "languages": {
      "en": "/mattress-sales",
      "es": "/es/mattress-sales",
      "x-default": "/mattress-sales"
    }
  },
  "openGraph": {
    "title": "Sleep Better. Save More. Shop Local.",
    "description": "You’re in the right place. At Snooze Mattress + Wellness, we help you find the perfect mattress at the perfect price — without pressure, gimmicks, or confusing fine print. Whether you’re upgrading your master bedroom, shopping for a guest room, or finally replacing that sagging mattress, we make it simple, affordable, and comfortable.",
    "url": "/mattress-sales",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
