// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Deja de Adivinar. Empieza a Dormir Mejor Esta Noche.",
  "description": "En Snooze Mattress + Wellness usamos la tecnología Dream Mapping, respaldada por la ciencia, para encontrar el colchón hecho a la medida de tu cuerpo — en solo 5 minutos. Sin presión. Sin adivinanzas. Solo un sueño profundo y reparador.",
  "alternates": {
    "canonical": "/es/about-us",
    "languages": {
      "en": "/about-us",
      "es": "/es/about-us",
      "x-default": "/about-us"
    }
  },
  "openGraph": {
    "title": "Deja de Adivinar. Empieza a Dormir Mejor Esta Noche.",
    "description": "En Snooze Mattress + Wellness usamos la tecnología Dream Mapping, respaldada por la ciencia, para encontrar el colchón hecho a la medida de tu cuerpo — en solo 5 minutos. Sin presión. Sin adivinanzas. Solo un sueño profundo y reparador.",
    "url": "/es/about-us",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
