// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Mejora tu Descanso con Bases Ajustables para Colchón",
  "description": "Las bases ajustables de Snooze Mattress + Wellness en McAllen están diseñadas para mejorar la comodidad, el soporte y la calidad de tu sueño. Con posiciones ajustables de cabeza y pies, ayudan a aliviar la presión, reducir los ronquidos, mejorar la circulación y mantener una postura más saludable al dormir.",
  "alternates": {
    "canonical": "/es/adjustable-mattress-bases",
    "languages": {
      "en": "/adjustable-mattress-bases",
      "es": "/es/adjustable-mattress-bases",
      "x-default": "/adjustable-mattress-bases"
    }
  },
  "openGraph": {
    "title": "Mejora tu Descanso con Bases Ajustables para Colchón",
    "description": "Las bases ajustables de Snooze Mattress + Wellness en McAllen están diseñadas para mejorar la comodidad, el soporte y la calidad de tu sueño. Con posiciones ajustables de cabeza y pies, ayudan a aliviar la presión, reducir los ronquidos, mejorar la circulación y mantener una postura más saludable al dormir.",
    "url": "/es/adjustable-mattress-bases",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/697bd240d5b65e6fefba8139.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
