// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Sleep Better, Recline Smarter with the Zcliner®",
  "description": "Discover a new way to rest with the SleepRecliner (Zcliner®) by Flexsteel, exclusively available at Snooze Mattress + Wellness in McAllen. More than just a recliner, the Zcliner® combines advanced comfort technology with therapeutic positioning to deliver restorative sleep and superior support.",
  "alternates": {
    "canonical": "/sleep-recliner",
    "languages": {
      "en": "/sleep-recliner",
      "es": "/es/sleep-recliner",
      "x-default": "/sleep-recliner"
    }
  },
  "openGraph": {
    "title": "Sleep Better, Recline Smarter with the Zcliner®",
    "description": "Discover a new way to rest with the SleepRecliner (Zcliner®) by Flexsteel, exclusively available at Snooze Mattress + Wellness in McAllen. More than just a recliner, the Zcliner® combines advanced comfort technology with therapeutic positioning to deliver restorative sleep and superior support.",
    "url": "/sleep-recliner",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
