// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Sleep Better, Recline Smarter with the Zcliner®",
  "description": "Discover a new way to rest with the SleepRecliner (Zcliner®) by Flexsteel, exclusively available at Snooze Mattress + Wellness in McAllen. More than just a recliner, the Zcliner® combines advanced comfort technology with therapeutic positioning to deliver restorative sleep and superior support.",
  "alternates": {
    "canonical": "/sleep-recliner",
    "languages": {
      "en": "/sleep-recliner",
      "es": "/es/sleep-recliner",
      "x-default": "/sleep-recliner"
    }
  },
  "openGraph": {
    "title": "Sleep Better, Recline Smarter with the Zcliner®",
    "description": "Discover a new way to rest with the SleepRecliner (Zcliner®) by Flexsteel, exclusively available at Snooze Mattress + Wellness in McAllen. More than just a recliner, the Zcliner® combines advanced comfort technology with therapeutic positioning to deliver restorative sleep and superior support.",
    "url": "/sleep-recliner",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4c722007d7fffba3f9.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/6998cd2220c03538d469a1f8.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
