// Generated by scripts/convert.mjs — edit overrides/overrides.json ("site") instead.
export const SITE = {
  phone: "(956) 303-3666",
  phoneHref: "tel:+19563033666",
  logo: "/assets/lcimg/image/f_webp/q_80/r_1200/u/filesafe/qR8peonBlnjGI3ZuLHQP/media/8d16458d-661d-4d16-bec0-14dea766bf45.webp",
  logoAlt: "Snooze Mattress + Wellness",
  featureImage: "/assets/lcimg/image/f_webp/q_80/r_640/u/filesafe/ARD47WoZpqaZSQ9MSxLD/media/695fbfed-24ba-4132-b604-2e6042bbb83f.jpeg",
} as const;
