// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Elevate Your Sleep with Adjustable Mattress Bases",
  "description": "Adjustable mattress bases at Snooze Mattress + Wellness in Brownsville, are designed to enhance comfort, support, and overall sleep quality. With customizable head and foot positioning, adjustable bases help relieve pressure, reduce snoring, improve circulation, and support healthier sleep posture.",
  "alternates": {
    "canonical": "/adjustable-mattress-bases",
    "languages": {
      "en": "/adjustable-mattress-bases",
      "es": "/es/adjustable-mattress-bases",
      "x-default": "/adjustable-mattress-bases"
    }
  },
  "openGraph": {
    "title": "Elevate Your Sleep with Adjustable Mattress Bases",
    "description": "Adjustable mattress bases at Snooze Mattress + Wellness in Brownsville, are designed to enhance comfort, support, and overall sleep quality. With customizable head and foot positioning, adjustable bases help relieve pressure, reduce snoring, improve circulation, and support healthier sleep posture.",
    "url": "/adjustable-mattress-bases",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a9a0fb7c6699665d1.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
