// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Stop Guessing. Start Sleeping Better Tonight.",
  "description": "At Snooze Mattress + Wellness, we use science-backed Dream Mapping technology to find the mattress that's perfectly built for your body — in 5 minutes flat. No pressure. No guesswork. Just deep, restorative sleep.",
  "alternates": {
    "canonical": "/about-us",
    "languages": {
      "en": "/about-us",
      "es": "/es/about-us",
      "x-default": "/about-us"
    }
  },
  "openGraph": {
    "title": "Stop Guessing. Start Sleeping Better Tonight.",
    "description": "At Snooze Mattress + Wellness, we use science-backed Dream Mapping technology to find the mattress that's perfectly built for your body — in 5 minutes flat. No pressure. No guesswork. Just deep, restorative sleep.",
    "url": "/about-us",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e0dae8153630a3751.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
