// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Política de Privacidad",
  "description": "Snooze Mattress Company – McAllen (“la Empresa”, “nosotros” o “nuestro”) respeta tu privacidad y se compromete a proteger tu información personal. Esta Política de Privacidad describe cómo recopilamos, usamos y compartimos la información cuando visitas nuestro sitio web, nos contactas o utilizas nuestros servicios.",
  "alternates": {
    "canonical": "/es/privacy-policy-page-1",
    "languages": {
      "en": "/privacy-policy-page-1",
      "es": "/es/privacy-policy-page-1",
      "x-default": "/privacy-policy-page-1"
    }
  },
  "openGraph": {
    "title": "Política de Privacidad",
    "description": "Snooze Mattress Company – McAllen (“la Empresa”, “nosotros” o “nuestro”) respeta tu privacidad y se compromete a proteger tu información personal. Esta Política de Privacidad describe cómo recopilamos, usamos y compartimos la información cuando visitas nuestro sitio web, nos contactas o utilizas nuestros servicios.",
    "url": "/es/privacy-policy-page-1",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
