// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import PageClient from './client';

export const metadata: Metadata = {
  "title": "Los Mejores Colchones en McAllen",
  "description": "Encontrar el colchón perfecto en McAllen no tiene por qué ser complicado. En Snooze Mattress + Wellness lo hacemos simple y personal. Desde comodidad de lujo y tecnología de sueño avanzada hasta opciones económicas, nuestra tienda en McAllen tiene colchones para cada estilo de descanso y presupuesto.",
  "alternates": {
    "canonical": "/es/mattresses",
    "languages": {
      "en": "/mattresses",
      "es": "/es/mattresses",
      "x-default": "/mattresses"
    }
  },
  "openGraph": {
    "title": "Los Mejores Colchones en McAllen",
    "description": "Encontrar el colchón perfecto en McAllen no tiene por qué ser complicado. En Snooze Mattress + Wellness lo hacemos simple y personal. Desde comodidad de lujo y tecnología de sueño avanzada hasta opciones económicas, nuestra tienda en McAllen tiene colchones para cada estilo de descanso y presupuesto.",
    "url": "/es/mattresses",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca46722007d7fffba363.png.webp"
  }
};

export default function Page() {
  return <PageClient />;
}
