// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Mejora tu Descanso con Almohadas Premium en Brownsville",
  "description": "La almohada correcta hace toda la diferencia. En Snooze Mattress + Wellness tenemos la mejor selección de almohadas premium de Brownsville, diseñadas para acunar tu cabeza, dar soporte a tu cuello y transformar tu descanso cada noche.",
  "alternates": {
    "canonical": "/es/pillows",
    "languages": {
      "en": "/pillows",
      "es": "/es/pillows",
      "x-default": "/pillows"
    }
  },
  "openGraph": {
    "title": "Mejora tu Descanso con Almohadas Premium en Brownsville",
    "description": "La almohada correcta hace toda la diferencia. En Snooze Mattress + Wellness tenemos la mejor selección de almohadas premium de Brownsville, diseñadas para acunar tu cabeza, dar soporte a tu cuello y transformar tu descanso cada noche.",
    "url": "/es/pillows",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
