// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Flexible Mattress Payment Plans at Snooze Mattress Company",
  "description": "At Snooze Mattress Company – McAllen, we make it easy to upgrade your sleep with flexible mattress payment options. Whether you’re purchasing a new mattress, adjustable base, or full sleep system, we offer financing solutions designed to fit a wide range of budgets and credit profiles. Better sleep shouldn’t wait.",
  "alternates": {
    "canonical": "/mattress-financing",
    "languages": {
      "en": "/mattress-financing",
      "es": "/es/mattress-financing",
      "x-default": "/mattress-financing"
    }
  },
  "openGraph": {
    "title": "Flexible Mattress Payment Plans at Snooze Mattress Company",
    "description": "At Snooze Mattress Company – McAllen, we make it easy to upgrade your sleep with flexible mattress payment options. Whether you’re purchasing a new mattress, adjustable base, or full sleep system, we offer financing solutions designed to fit a wide range of budgets and credit profiles. Better sleep shouldn’t wait.",
    "url": "/mattress-financing",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
