// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Duerme Mejor. Ahorra Más. Compra Local.",
  "description": "Estás en el lugar correcto. En Snooze Mattress + Wellness, te ayudamos a encontrar el colchón perfecto al precio perfecto — sin presiones, trucos ni letras chiquitas confusas. Ya sea que estés renovando tu recámara principal, buscando algo para el cuarto de visitas o por fin reemplazando ese colchón hundido, lo hacemos sencillo, accesible y cómodo.",
  "alternates": {
    "canonical": "/es/mattress-sales",
    "languages": {
      "en": "/mattress-sales",
      "es": "/es/mattress-sales",
      "x-default": "/mattress-sales"
    }
  },
  "openGraph": {
    "title": "Duerme Mejor. Ahorra Más. Compra Local.",
    "description": "Estás en el lugar correcto. En Snooze Mattress + Wellness, te ayudamos a encontrar el colchón perfecto al precio perfecto — sin presiones, trucos ni letras chiquitas confusas. Ya sea que estés renovando tu recámara principal, buscando algo para el cuarto de visitas o por fin reemplazando ese colchón hundido, lo hacemos sencillo, accesible y cómodo.",
    "url": "/es/mattress-sales",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
