// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Protege tu Colchón, Protege tu Inversión",
  "description": "Un colchón de calidad merece protección de calidad. En Snooze Mattress + Wellness en Brownsville, nuestros protectores de colchón premium cuidan tu cama contra derrames, manchas, alérgenos y el desgaste diario, sin perder la comodidad y la sensación que tanto te gusta.",
  "alternates": {
    "canonical": "/es/mattress-protectors",
    "languages": {
      "en": "/mattress-protectors",
      "es": "/es/mattress-protectors",
      "x-default": "/mattress-protectors"
    }
  },
  "openGraph": {
    "title": "Protege tu Colchón, Protege tu Inversión",
    "description": "Un colchón de calidad merece protección de calidad. En Snooze Mattress + Wellness en Brownsville, nuestros protectores de colchón premium cuidan tu cama contra derrames, manchas, alérgenos y el desgaste diario, sin perder la comodidad y la sensación que tanto te gusta.",
    "url": "/es/mattress-protectors",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a6572a4cf4c8db3e8.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
