// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Términos y Condiciones",
  "description": "Bienvenido a Snooze Mattress + Wellness – McAllen (“la Empresa”, “nosotros” o “nuestro”). Al acceder o usar este sitio web (“Sitio Web”), aceptas los siguientes Términos y Condiciones. Si no estás de acuerdo, por favor no utilices el Sitio Web.",
  "alternates": {
    "canonical": "/es/terms-conditions",
    "languages": {
      "en": "/terms-conditions",
      "es": "/es/terms-conditions",
      "x-default": "/terms-conditions"
    }
  },
  "openGraph": {
    "title": "Términos y Condiciones",
    "description": "Bienvenido a Snooze Mattress + Wellness – McAllen (“la Empresa”, “nosotros” o “nuestro”). Al acceder o usar este sitio web (“Sitio Web”), aceptas los siguientes Términos y Condiciones. Si no estás de acuerdo, por favor no utilices el Sitio Web.",
    "url": "/es/terms-conditions",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a7c8daffe4291bd100eddea.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
