// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Elevate Your Sleep with Premium Pillows in Brownsville",
  "description": "The right pillow makes all the difference. At Snooze Mattress + Wellness, we offer Brownsville's finest selection of premium pillows designed to cradle your head, support your neck, and transform your nightly rest.",
  "alternates": {
    "canonical": "/pillows",
    "languages": {
      "en": "/pillows",
      "es": "/es/pillows",
      "x-default": "/pillows"
    }
  },
  "openGraph": {
    "title": "Elevate Your Sleep with Premium Pillows in Brownsville",
    "description": "The right pillow makes all the difference. At Snooze Mattress + Wellness, we offer Brownsville's finest selection of premium pillows designed to cradle your head, support your neck, and transform your nightly rest.",
    "url": "/pillows",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4a4fe74193541e425c.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} />;
}
