// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Planes de Pago Flexibles para Colchones en Snooze Mattress Company",
  "description": "En Snooze Mattress Company – McAllen te facilitamos mejorar tu descanso con opciones de pago flexibles. Ya sea que compres un colchón nuevo, una base ajustable o un sistema de sueño completo, tenemos soluciones de financiamiento pensadas para todo tipo de presupuestos e historiales de crédito. Dormir mejor no debería esperar.",
  "alternates": {
    "canonical": "/es/mattress-financing",
    "languages": {
      "en": "/mattress-financing",
      "es": "/es/mattress-financing",
      "x-default": "/mattress-financing"
    }
  },
  "openGraph": {
    "title": "Planes de Pago Flexibles para Colchones en Snooze Mattress Company",
    "description": "En Snooze Mattress Company – McAllen te facilitamos mejorar tu descanso con opciones de pago flexibles. Ya sea que compres un colchón nuevo, una base ajustable o un sistema de sueño completo, tenemos soluciones de financiamiento pensadas para todo tipo de presupuestos e historiales de crédito. Dormir mejor no debería esperar.",
    "url": "/es/mattress-financing",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4e747464c6b3a3be10.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/69a1cbdf917b4b217201b5ff.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
