#!/usr/bin/env node
/**
 * Store relocation: Brownsville → McAllen.
 *
 * The pages under app/ are generated by scripts/convert.mjs from the Brownsville clone, so every
 * location-specific value (city name, street address, phone, e-mail, social links, hours, map links)
 * is rewritten here, after generation. The same rules run over the hand-written files (components/,
 * lib/, overrides/) so one mapping is the single source of truth.
 *
 *   node scripts/relocate.mjs            # rewrite in place
 *   node scripts/relocate.mjs --check    # only report leftovers, change nothing
 *
 * convert.mjs calls relocate() as its last step, so `npm run convert` keeps producing McAllen pages.
 * The Spanish dictionaries (overrides/i18n/es.*.json) are rewritten VALUES-ONLY: their keys must keep
 * matching the English clone text or the translation lookup breaks on the next conversion.
 * The hand-written site data lives in lib/location.ts (footer, JSON-LD); keep both in sync.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const NEW = {
  city: 'McAllen',
  street: '7913 North 10th Street, Suite 130',
  cityStateZip: 'McAllen, TX 78504',
  zip: '78504',
  phone: '(956) 586-5646',
  phoneDigits: '9565865646',
  phoneIntl: '+1 956-586-5646',
  email: 'northmcallen@snoozemattresscompany.com',
  facebook: 'https://www.facebook.com/p/Snooze-Mattress-Wellness-61575812121380/',
  instagram: 'https://www.instagram.com/snoozemcallen',
  youtube: 'https://www.youtube.com/@SnoozeMcAllen',
  mapsQuery: '7913+North+10th+Street,+Suite+130,+McAllen,+TX+78504',
  hoursEn: ['Mon – Sat 10 AM – 7 PM', 'Sunday 12 – 6 PM'],
  hoursEs: ['Lun – Sáb 10 AM – 7 PM', 'Domingo 12 – 6 PM'],
};
NEW.mapLink = `https://maps.google.com/?q=${NEW.mapsQuery}`;
NEW.mapEmbed = `https://maps.google.com/maps?q=${NEW.mapsQuery}&z=15&output=embed`;

const OLD_EMAIL_PLACEHOLDER = 'http://tfrench.snoozemattresscompany.com/';
const OLD_SITE_URL = 'https://brownsville-webiste.vercel.app';

/* The generated content.ts files hold HTML twice: once as the page markup inside a JS string
   (quotes as \") and once inside the Nuxt payload JSON string (tags as \u003C, quotes as \\\").
   Rules that insert markup are emitted in both encodings. */
const encMarkup = (html) => html.replace(/"/g, '\\"');
const encPayload = (html) => html.replace(/</g, '\\\\u003C').replace(/"/g, '\\\\\\"');
const mailto = `<a href="mailto:${NEW.email}">${NEW.email}</a>`;

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const lit = (from, to) => [new RegExp(esc(from), 'g'), to];

/** Ordered: specific patterns first, the bare city name last. */
export const RULES = [
  // ---- phone
  [/tel:\+19563033666/g, `tel:+1${NEW.phoneDigits}`],
  [/\+1 956-30[36]-3666/g, NEW.phoneIntl],
  [/9563033666/g, NEW.phoneDigits],
  [/\(956\) 30[36]-3666/g, NEW.phone],
  [/30[36]-3666/g, NEW.phone.slice(6)],

  // ---- address, map links
  [/3831\+Frontage\+Road\+Ste\+2,\+Brownsville,\+TX\+78520/g, NEW.mapsQuery],
  lit('https://share.google/tRQVAaAurSFu6jvKl', NEW.mapLink),
  lit('https://maps.app.goo.gl/KevCK7WVkFbBDRir5', NEW.mapLink),
  [/3831 Frontage (?:Road|Rd\.?),? (?:Suite|Ste\.?) 2/g, NEW.street],
  [/Brownsville, TX 78520/g, NEW.cityStateZip],
  [/TX 78520/g, `TX ${NEW.zip}`],
  [/(\\?")78520(\\?")/g, `$1${NEW.zip}$2`], // JSON-LD postalCode (quotes are escaped inside the payload string)

  // ---- e-mail (the legal pages carried a placeholder URL where the address belongs)
  lit('brownsville@snoozemattresscompany.com', NEW.email),
  ...['Email', 'Correo'].flatMap((label) => [
    lit(encPayload(`<br>${label}: ${OLD_EMAIL_PLACEHOLDER}`), encPayload(`<br>${label}: ${mailto}`)),
    lit(encMarkup(`<br>${label}: ${OLD_EMAIL_PLACEHOLDER}`), encMarkup(`<br>${label}: ${mailto}`)),
  ]),
  lit(encPayload(`${OLD_EMAIL_PLACEHOLDER}<br>`), encPayload(`${mailto}<br>`)),
  lit(encMarkup(`${OLD_EMAIL_PLACEHOLDER}<br>`), encMarkup(`${mailto}<br>`)),
  lit(OLD_EMAIL_PLACEHOLDER, NEW.email),
  lit('https://tfrench.snoozemattresscompany.com/', `${OLD_SITE_URL}/`),

  // ---- social profiles
  [/https:\/\/www\.instagram\.com\/snoozebrownsville\/?/g, NEW.instagram],
  lit('https://www.facebook.com/profile.php?id=61593118197488', NEW.facebook),

  // ---- hours (one consistent format; the clone uses narrow no-break spaces, U+202F, before AM/PM)
  [/Mon[\s  ]-[\s  ]Sat[\s  ]10[\s  ]?AM–7[\s  ]?PM/g, NEW.hoursEn[0]],
  [/Sunday[\s  ]12–6[\s  ]?PM/g, NEW.hoursEn[1]],
  [/Lun[\s  ]-[\s  ]Sáb[\s  ]10[\s  ]?AM–7[\s  ]?PM/g, NEW.hoursEs[0]],
  [/Domingo[\s  ]12–6[\s  ]?PM/g, NEW.hoursEs[1]],

  // ---- city name: grammar fixes first ("in the Brownsville." / "en el Brownsville ." / "Brownsville 's")
  [/in the Brownsville ?\.\.?/g, `in ${NEW.city}.`],
  [/en el Brownsville ?\./g, `en ${NEW.city}.`],
  [/Brownsville ?(['’])s/g, `${NEW.city}$1s`],
  [/BROWNSVILLE/g, NEW.city.toUpperCase()],
  [/Brownsville/g, NEW.city],

  // ---- CRM widget ids of the old location's sub-account (the live embeds come from overrides.json → widgets; these
  //      catch the clone's leftover references: form field CSS ids, payload element config)
  lit('cUKX8RzffonzLORrzIhS', '0BTnYKylVR6OcWJug3r8'), // Optin form
  lit('7oZZd8zPpnUYzsMS4VZM', 'lrAns7Z8j3vEJW3DC0Yr'), // Dream Mapping booking calendar
  lit('6a721a99bae62cba6f021c61', '67f5847f79c4ab793baf0087'), // reviews widget

  // ---- home hero, phone copy: the city name, like the desktop copy ("McAllen, Get / Custom-Fit for / …"); markup and
  //      payload encodings of the heading HTML (the desktop copy already starts with "McAllen, " and is not matched)
  [/(>|\\u003E)Get (<\/span>|\\u003C\/span>)(?=(?:<|\\u003C)span[^>]*>Custom-Fit)/g, `$1${NEW.city}, Get $2`],
  [/(>|\\u003E)Recibe (<\/span>|\\u003C\/span>)(?=(?:<|\\u003C)span[^>]*>Ajuste a tu Medida)/g, `$1${NEW.city}, Recibe $2`],

  // ---- live domain (canonicals, sitemap, robots, JSON-LD, the Privacy Policy link on the Terms pages)
  lit('brownsville-webiste.vercel.app', 'mcallen.snoozemattresscompany.com'),
  // the client's copy linked the Rockwall store (Terms → Privacy Policy, and a "Snooze Mattress Company" link on every
  // page); slashes may be JSON-escaped (/) inside the payload
  [/https:(\/\/|\\\\u002F\\\\u002F|\\u002F\\u002F)rockwall\.snoozemattresscompany\.com/g, 'https:$1mcallen.snoozemattresscompany.com'],

  // ---- project name
  lit('"name": "brownsville-next"', '"name": "mcallen-next"'),
];

/** Leftover patterns reported by --check (and by the final sweep). */
export const LEFTOVER = /brownsville|303-3666|3033666|306-3666|3831 Frontage|3831\+Frontage|78520|snoozebrownsville|tfrench\./gi;
/** Leftovers that are expected: the source clone host, the current Vercel deployment host, the clone path. */
export const LEFTOVER_OK = /brownsville-webiste|brownsville\.snoozemattresscompany\.com|C:\/clones\/brownsville|unsplash\.com\/photo-1597852075012/;

const SKIP_DIRS = new Set(['node_modules', '.next', '.git', '.vercel', 'verify-out', 'public']);
const SKIP_FILES = new Set(['relocate.mjs', 'asset-map.json', 'conversion-report.json', 'tsconfig.tsbuildinfo']);
const TEXT = /\.(ts|tsx|mjs|js|json|html|css|md)$/;
const DICT = /^es(\.part-\d+|\.extra)\.json$/; // overrides/i18n dictionaries: values only

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(e.name)) continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (TEXT.test(e.name) && !SKIP_FILES.has(e.name)) out.push(p);
  }
  return out;
}

export function applyRules(text) {
  let out = text;
  for (const [re, to] of RULES) out = out.replace(re, to);
  return out;
}

function relocateFile(file, check) {
  const rel = path.relative(ROOT, file).replace(/\\/g, '/');
  const src = fs.readFileSync(file, 'utf8');
  let next;
  if (DICT.test(path.basename(file)) && rel.startsWith('overrides/i18n/')) {
    const dict = JSON.parse(src);
    for (const k of Object.keys(dict)) if (typeof dict[k] === 'string') dict[k] = applyRules(dict[k]);
    const indent = (src.match(/^\{\r?\n(\s+)"/) || [, ' '])[1].length;
    next = JSON.stringify(dict, null, indent) + (src.endsWith('\n') ? '\n' : '');
  } else if (rel.startsWith('overrides/i18n/')) {
    return null; // chunks / segments / missing: extraction artifacts of the English clone
  } else {
    next = applyRules(src);
  }
  if (next !== src && !check) fs.writeFileSync(file, next);
  return next !== src ? rel : null;
}

export function leftovers(text) {
  const found = [];
  let m;
  const re = new RegExp(LEFTOVER.source, 'gi');
  while ((m = re.exec(text))) {
    const ctx = text.slice(Math.max(0, m.index - 40), m.index + m[0].length + 40).replace(/\s+/g, ' ');
    if (!LEFTOVER_OK.test(ctx)) found.push(ctx);
  }
  return found;
}

export function relocate(root = ROOT, { check = false, quiet = false } = {}) {
  const changed = [];
  const left = {};
  for (const f of walk(root)) {
    const c = relocateFile(f, check);
    if (c) changed.push(c);
    const rel = path.relative(root, f).replace(/\\/g, '/');
    if (rel.startsWith('overrides/i18n/') && !DICT.test(path.basename(f))) continue;
    // dictionaries: only the Spanish values matter (the keys are the English clone text by design)
    const text = DICT.test(path.basename(f)) ? Object.values(JSON.parse(fs.readFileSync(f, 'utf8'))).join('\n') : fs.readFileSync(f, 'utf8');
    const l = leftovers(text);
    if (l.length) left[rel] = l;
  }
  if (!quiet) {
    console.log(`relocate: ${check ? 'would change' : 'changed'} ${changed.length} file(s)`);
    const files = Object.keys(left);
    if (files.length) {
      console.log(`relocate: ${files.length} file(s) still mention the old location:`);
      for (const f of files) for (const c of left[f]) console.log(`  ${f}: …${c}…`);
    }
  }
  return { changed, leftovers: left };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  relocate(ROOT, { check: process.argv.includes('--check') });
}
