// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Descubre Qué Interrumpe tu Sueño, Desde Casa",
  "description": "¿Batallas con ronquidos, cansancio o noches inquietas? El Kit de Prueba de Sueño en Casa de SleepCorner, disponible en Snooze Mattress + Wellness en McAllen, te da respuestas sin la molestia de un laboratorio del sueño. Esta prueba fácil de usar y aprobada por la FDA monitorea tus patrones de sueño durante la noche y la revisan profesionales del sueño certificados para identificar posibles trastornos como la apnea del sueño.",
  "alternates": {
    "canonical": "/es/at-home-sleep-test-kit-by-sleepcorner",
    "languages": {
      "en": "/at-home-sleep-test-kit-by-sleepcorner",
      "es": "/es/at-home-sleep-test-kit-by-sleepcorner",
      "x-default": "/at-home-sleep-test-kit-by-sleepcorner"
    }
  },
  "openGraph": {
    "title": "Descubre Qué Interrumpe tu Sueño, Desde Casa",
    "description": "¿Batallas con ronquidos, cansancio o noches inquietas? El Kit de Prueba de Sueño en Casa de SleepCorner, disponible en Snooze Mattress + Wellness en McAllen, te da respuestas sin la molestia de un laboratorio del sueño. Esta prueba fácil de usar y aprobada por la FDA monitorea tus patrones de sueño durante la noche y la revisan profesionales del sueño certificados para identificar posibles trastornos como la apnea del sueño.",
    "url": "/es/at-home-sleep-test-kit-by-sleepcorner",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
    ],
    "locale": "es_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4d722007d7fffba40f.png"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/6998cc589df4c153d0a468bf.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
