// Generated by scripts/convert.mjs — do not edit by hand. Regenerate with `npm run convert`.
import type { Metadata } from 'next';
import { GhlPage } from '@/components/GhlPage';
import { HEAD_HTML, BODY_HTML, SCRIPTS } from './content';

export const metadata: Metadata = {
  "title": "Wrap Yourself in Luxury Every Night",
  "description": "The right sheets can transform your sleep experience. At Snooze Mattress + Wellness in McAllen, our premium sheet collection combines softness, breathability, and durability to create the ultimate sleep sanctuary.",
  "alternates": {
    "canonical": "/premium-sheets",
    "languages": {
      "en": "/premium-sheets",
      "es": "/es/premium-sheets",
      "x-default": "/premium-sheets"
    }
  },
  "openGraph": {
    "title": "Wrap Yourself in Luxury Every Night",
    "description": "The right sheets can transform your sleep experience. At Snooze Mattress + Wellness in McAllen, our premium sheet collection combines softness, breathability, and durability to create the ultimate sleep sanctuary.",
    "url": "/premium-sheets",
    "type": "website",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4b4fe74193541e4272.png.webp"
    ],
    "locale": "en_US"
  },
  "twitter": {
    "card": "summary_large_image",
    "images": [
      "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4b4fe74193541e4272.png.webp"
    ]
  },
  "icons": {
    "icon": "/assets/filesafe/qR8peonBlnjGI3ZuLHQP/media/695b9e7d17768458ae206a19.png"
  },
  "other": {
    "image": "/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a90ca4b4fe74193541e4272.png.webp"
  }
};

export default function Page() {
  return <GhlPage headHtml={HEAD_HTML} bodyHtml={BODY_HTML} scripts={SCRIPTS} preload={[{"href":"/assets/filesafe/ARD47WoZpqaZSQ9MSxLD/media/6994d95854da044f3c95c763.png.webp","media":"(min-width: 768px)"},{"href":"/assets/filesafe/BljrSmLCnm4gF9LpsTRZ/media/6a9899f9da522bf173a9bd91.png.webp","media":"(max-width: 767px)"}]} />;
}
